[build]
  command = "npm run build"
  publish = "front-end/build"
  directory = "front-end"

[build.environment]
  REACT_APP_API_URL = "https://proyecto-unilever-backend.onrender.com"
  REACT_APP_ADMIN_USER = "admin"
  REACT_APP_ADMIN_PASSWORD = "unilever2024"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200