[build]
  command = "cd front-end && npm install && npm run build"
  publish = "front-end/build"

[build.environment]
  REACT_APP_API_URL = "https://proyecto-unilever-backend.onrender.com"
  REACT_APP_ADMIN_USER = "admin"
  REACT_APP_ADMIN_PASSWORD = "unilever2024"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200